/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 arrow.gltf 
Author: Farid (https://sketchfab.com/farid1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-red-arrow-10d31661bb98445a9a8bf45c018682f4
Title: Simple Red Arrow
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('arrow/arrow.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group scale={100}>
          <mesh geometry={nodes.node_id30_Material_0.geometry} material={materials.Material} rotation={[-Math.PI, 0, Math.PI]} scale={0.1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/arrow.gltf')
