### Success
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "fullName": "john doe",
  "email": "carlos@gmail.com",
  "password": "12345678"
}

### Invalid email
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "fullName": "Carlos Sosa",
  "email": "invalid-email",
  "password": "12345678"
}

### Invalid full name by length
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "fullName": "ab",
  "email": "carlos@gmail.com",
  "password": "12345678"
}

### Invalid full name by special character
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "fullName": "carlos 123",
  "email": "carlos@gmail.com",
  "password": "12345678"
}


### Invalid password
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "fullName": "Carlos Sosa",
  "email": "carlos@gmail.com",
  "password": "1234567"
}

### Missing full name & email
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "password": "1234567"
}