/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 chart.gltf 
Author: rikugo.studio (https://sketchfab.com/rikugo.studio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/data-chart-infographics-60a66b3b47d54aaa917378c7380ebe60
Title: Data Chart Infographics
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('chart/chart.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={5.278}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Garis} position={[-0.055, 0, 0]} scale={[0.009, 0.5, 0.022]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Black} position={[0, -0.075, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.071, 0.071, 0.071]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Kanvas} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.765]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.Graphic} position={[-0.044, -0.022, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.3} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/chart.gltf')
