/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 cangrejo.gltf 
Author: guntuy3 (https://sketchfab.com/guntuy3)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mr-krab-money-33fab92081ef429d98a8e531f76c540c
Title: Mr. Krab Money
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('cangrejo/cangrejo.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-1.031, 0, -2.59]} rotation={[0, -0.452, 0]} scale={1.589}>
          <mesh geometry={nodes.Circle_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.Circle_1.geometry} material={materials.Hand} />
        </group>
        <group position={[-2.426, 0, -0.891]} rotation={[0, -0.669, 0]}>
          <mesh geometry={nodes.Circle001_0.geometry} material={materials['Sun.001']} />
          <mesh geometry={nodes.Circle001_1.geometry} material={materials.Body} />
        </group>
        <group position={[-1.314, 0, -4.614]} scale={0.435}>
          <mesh geometry={nodes.Circle002_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.Circle002_1.geometry} material={materials.Hand} />
        </group>
        <group position={[-1.932, -1.031, -2.601]} rotation={[1.073, 0.436, -0.62]} scale={0.244}>
          <mesh geometry={nodes.Circle003_0.geometry} material={materials.Hand} />
          <mesh geometry={nodes.Circle003_1.geometry} material={materials.Body} />
        </group>
        <group position={[-0.619, 0.741, -1.31]} rotation={[1.224, 1.287, 2.001]} scale={[-0.244, 0.244, 0.244]}>
          <mesh geometry={nodes.Circle004_0.geometry} material={materials.Hand} />
          <mesh geometry={nodes.Circle004_1.geometry} material={materials.Body} />
        </group>
        <mesh geometry={nodes.Plane_0.geometry} material={materials.Body} position={[-2.247, -0.315, -1.09]} rotation={[1.328, 0.04, -1.281]} scale={0.071} />
        <mesh geometry={nodes.Cube_0.geometry} material={materials.Kantung} position={[0.612, -1.938, 0.506]} rotation={[0.255, -0.063, -0.485]} />
        <mesh geometry={nodes.Circle005_0.geometry} material={materials.Kantung} position={[1.513, -3.039, 3.791]} rotation={[0.338, 0.445, -0.17]} />
        <mesh geometry={nodes.Torus_0.geometry} material={materials.Kantung} />
        <mesh geometry={nodes.Circle006_0.geometry} material={materials.Body} position={[-1.031, 0, -2.59]} rotation={[0, -0.452, 0]} scale={1.589} />
        <mesh geometry={nodes.Circle007_0.geometry} material={materials.Body} position={[-1.031, 0, -2.59]} rotation={[0, -0.452, 0]} scale={1.589} />
        <mesh geometry={nodes.Plane002_0.geometry} material={materials.Uang} position={[-4.509, -0.348, 0.146]} rotation={[2.871, -0.793, -2.931]} />
        <mesh geometry={nodes.Plane001_0.geometry} material={materials.Uang} position={[1.035, -4.03, -3.989]} rotation={[-0.585, -0.832, -0.219]} />
        <mesh geometry={nodes.Plane003_0.geometry} material={materials.Uang} position={[3.216, 2.077, -1.081]} rotation={[-0.176, -0.435, 0.091]} />
        <mesh geometry={nodes.Plane004_0.geometry} material={materials.Uang} position={[-2.47, 3.633, -2.944]} rotation={[0.219, -0.417, 1.003]} />
        <mesh geometry={nodes.Plane005_0.geometry} material={materials.Uang} position={[5.297, -1.596, -4.191]} rotation={[-0.659, 0.328, 1.12]} />
        <mesh geometry={nodes.Circle008_0.geometry} material={materials.KOin} position={[4.214, -2.116, 2.449]} rotation={[0, Math.PI / 2, 0]} scale={0.245} />
        <mesh geometry={nodes.Circle009_0.geometry} material={materials.KOin} position={[3.825, -3.64, -0.643]} rotation={[2.175, 0.64, -2.203]} scale={0.245} />
        <mesh geometry={nodes.Circle010_0.geometry} material={materials.KOin} position={[-0.292, -2.949, -3.058]} rotation={[-3.095, -0.402, -2.227]} scale={0.245} />
        <mesh geometry={nodes.Circle011_0.geometry} material={materials.KOin} position={[2.702, 0.34, -3.989]} rotation={[-1.93, -0.295, 3.123]} scale={0.245} />
      </group>
    </group>
  )
}

useGLTF.preload('/cangrejo.gltf')
