/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 board.gltf 
Author: IIEPBblUI (https://sketchfab.com/IIEPBblUI)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/school-board-b21762689fe24652942e1b6f8751269a
Title: School board
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('board/board.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Bolts} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Bolts2} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Bolts3} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Metal2} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Metal3} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Plastic} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Plastic2} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Plastic3} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Plastic4}  />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Plastic5}  />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Volume143} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Wood}  />
      </group>
    </group>
  )
}

useGLTF.preload('/board.gltf')
