/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 panel_solar.gltf 
Author: Harri Snellman (https://sketchfab.com/rivetech)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/solar-panel-83483a66f8974d7e8f2e7bbde518d606
Title: Solar Panel
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('panel-solar/panel_solar.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SolarPanel_SolarPanel_0.geometry} material={materials.SolarPanel} position={[0, 12.206, 35.525]} rotation={[-Math.PI / 4, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/panel_solar.gltf')
