/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 trivia.gltf 
Author: crittaa (https://sketchfab.com/crittaa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/trivia-podium-316c947c0b54485bbd5edd29c73a6a00
Title: Trivia Podium
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('trivia/trivia.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.TriviaBase_lambert2_0.geometry} material={materials.lambert2} position={[-1.225, 4, 0]} scale={[0.777, 1.173, 0.539]} />
        <mesh geometry={nodes.TriviaButtonTrim_lambert5_0.geometry} material={materials.lambert5} position={[-2.984, 7.782, -1]} rotation={[0, 0, -0.643]} scale={[0.51, 0.173, 0.588]} />
        <mesh geometry={nodes.TriviaButton1_lambert5_0.geometry} material={materials.lambert5} position={[-2.984, 7.782, -1]} rotation={[0, 0, -0.643]} scale={[0.51, 0.173, 0.588]} />
        <mesh geometry={nodes.TriviaButton2_lambert4_0.geometry} material={materials.lambert4} position={[-2.984, 7.782, 1]} rotation={[0, 0, -0.643]} scale={[0.51, 0.173, 0.588]} />
        <mesh geometry={nodes.TriviaButtonTrim2_lambert4_0.geometry} material={materials.lambert4} position={[-2.984, 7.782, 1]} rotation={[0, 0, -0.643]} scale={[0.51, 0.173, 0.588]} />
        <mesh geometry={nodes.TriviaButton3_lambert6_0.geometry} material={materials.lambert6} position={[-1, 6.306, 1]} rotation={[0, 0, -0.643]} scale={[0.51, 0.173, 0.588]} />
        <mesh geometry={nodes.TriviaButtonTrim3_lambert6_0.geometry} material={materials.lambert6} position={[-1, 6.306, 1]} rotation={[0, 0, -0.643]} scale={[0.51, 0.173, 0.588]} />
        <mesh geometry={nodes.TriviaButton4_lambert7_0.geometry} material={materials.lambert7} position={[-1, 6.306, -1]} rotation={[0, 0, -0.643]} scale={[0.51, 0.173, 0.588]} />
        <mesh geometry={nodes.TriviaButtonTrim4_lambert7_0.geometry} material={materials.lambert7} position={[-1, 6.306, -1]} rotation={[0, 0, -0.643]} scale={[0.51, 0.173, 0.588]} />
      </group>
    </group>
  )
}

useGLTF.preload('/trivia.gltf')
