# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
    ecofunding

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
    - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
    MyHttpApi:
        Type: AWS::Serverless::HttpApi
        Properties:
            CorsConfiguration:
                AllowOrigins: "*"
                AllowHeaders: "*"
                AllowMethods: GET, POST, DELETE, PATCH

    getAllProjectsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/projects/get-all-items.getAll
            Runtime: nodejs20.x
            Architectures:
                - x86_64
            MemorySize: 128
            Timeout: 100
            Description: "Get all projects"
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref ProjectTable
            Environment:
                Variables:
                    PROJECT_TABLE: !Ref ProjectTable
            Events:
                Api:
                    Type: HttpApi
                    Properties:
                        Path: /projects
                        Method: GET

    createProjectFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/projects/put-item.createProjectHandler
            Runtime: nodejs20.x
            Architectures:
                - x86_64
            MemorySize: 128
            Timeout: 100
            Description: "Create project"
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref ProjectTable
                - DynamoDBCrudPolicy:
                      TableName: !Ref UserTable
            Environment:
                Variables:
                    PROJECT_TABLE: !Ref ProjectTable
                    USER_TABLE: !Ref UserTable
            Events:
                Api:
                    Type: HttpApi
                    Properties:
                        Path: /projects
                        Method: POST

    # DynamoDB table to store item: {id: &lt;ID&gt;, name: &lt;NAME&gt;}
    ProjectTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: Projects
            PrimaryKey:
                Name: projectId
                Type: String
            ProvisionedThroughput:
                ReadCapacityUnits: 2
                WriteCapacityUnits: 2

    UserTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: Users
            PrimaryKey:
                Name: userId
                Type: String
            ProvisionedThroughput:
                ReadCapacityUnits: 2
                WriteCapacityUnits: 2

    ApplicationResourceGroup:
        Type: AWS::ResourceGroups::Group
        Properties:
            Name:
                Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
            ResourceQuery:
                Type: CLOUDFORMATION_STACK_1_0
    ApplicationInsightsMonitoring:
        Type: AWS::ApplicationInsights::Application
        Properties:
            ResourceGroupName:
                Ref: ApplicationResourceGroup
            AutoConfigurationEnabled: "true"
Outputs:
    WebEndpoint:
        Description: API Gateway endpoint URL for Prod stage
        Value: !Sub "https://${MyHttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
